language: python  # this works for Linux but is an error on macOS or Windows

jobs:
  include:  # https://docs.travis-ci.com/user/reference/overview/ SO lists https://en.wikipedia.org/wiki/Ubuntu_version_history
    - name: "Python 3.8 on 16.04 Xenial Xerus"
      dist: xenial
      python: 3.8           # this works for Linux but is ignored on macOS or Windows}

    - name: "Python 3.8 on 14.04 Trusty Tahr"
      dist: trusty
      python: 3.5
#
    - name: "Python 3.8 on 12.04 Precise Pangolin"
      dist: precise
      python: 2.7

#    - name: "Python 3.8 on 18.04 Bionic Beaver"
#      dist: bionic
#      python: 3.8

install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements.txt

# command to run tests
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  # unit test
  - python3 -m pytest -v || python -m pytest -v
