git:
  submodules: false
  quiet: true
  depth: 3

language: python  # this works for Linux but is an error on macOS or Windows. We will specify that the language is Python.

cache: pip  # caching

jobs:
  include:  # https://docs.travis-ci.com/user/reference/overview/ SO lists https://en.wikipedia.org/wiki/Ubuntu_version_history
    - stage: "Tests in Linux"
    - name: "Python 3.6 on 16.04 Xenial Xerus"
      dist: xenial
      python: 3.6  # this works for Linux but is ignored on macOS or Windows

    - name: "Python 3.5 on 14.04 Trusty Tahr"
      dist: trusty
      python: 3.5

    - name: "Python 2.7 on 12.04 Precise Pangolin"
      dist: precise
      python: 2.7

    - name: "Python 3.8 on 18.04 Bionic Beaver"
      dist: bionic
      python: 3.8

    - stage: "Tests in other Platforms"
    - name: "Python 3.8.0 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

    - stage: deploy
      if: (branch = develop) AND (NOT (type IN (push, pull_request)))
      os: linux
      dist: xenial
      python: 3.8
      script:
        - echo "Deploying (for now)"

install:  # antes de ejecutar los test debemos crear el entorno virtual. command to run inside the virtual environment
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'. Command to install dependencies.
  - pip3 install -r requirements.txt  # Travis already creates a virtual environment and activates it. You don't need to do that.

# command to run tests
# 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script:
  # unit test. command run to test.
  - python3 -m pytest -v || python -m pytest -v
